// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: omni/omni/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateFetchEthData struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DataVal string `protobuf:"bytes,2,opt,name=dataVal,proto3" json:"dataVal,omitempty"`
}

func (m *MsgCreateFetchEthData) Reset()         { *m = MsgCreateFetchEthData{} }
func (m *MsgCreateFetchEthData) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFetchEthData) ProtoMessage()    {}
func (*MsgCreateFetchEthData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{0}
}
func (m *MsgCreateFetchEthData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFetchEthData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFetchEthData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFetchEthData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFetchEthData.Merge(m, src)
}
func (m *MsgCreateFetchEthData) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFetchEthData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFetchEthData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFetchEthData proto.InternalMessageInfo

func (m *MsgCreateFetchEthData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateFetchEthData) GetDataVal() string {
	if m != nil {
		return m.DataVal
	}
	return ""
}

type MsgCreateFetchEthDataResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateFetchEthDataResponse) Reset()         { *m = MsgCreateFetchEthDataResponse{} }
func (m *MsgCreateFetchEthDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateFetchEthDataResponse) ProtoMessage()    {}
func (*MsgCreateFetchEthDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{1}
}
func (m *MsgCreateFetchEthDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateFetchEthDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateFetchEthDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateFetchEthDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateFetchEthDataResponse.Merge(m, src)
}
func (m *MsgCreateFetchEthDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateFetchEthDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateFetchEthDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateFetchEthDataResponse proto.InternalMessageInfo

func (m *MsgCreateFetchEthDataResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateFetchEthData struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	DataVal string `protobuf:"bytes,3,opt,name=dataVal,proto3" json:"dataVal,omitempty"`
}

func (m *MsgUpdateFetchEthData) Reset()         { *m = MsgUpdateFetchEthData{} }
func (m *MsgUpdateFetchEthData) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateFetchEthData) ProtoMessage()    {}
func (*MsgUpdateFetchEthData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{2}
}
func (m *MsgUpdateFetchEthData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateFetchEthData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateFetchEthData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateFetchEthData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateFetchEthData.Merge(m, src)
}
func (m *MsgUpdateFetchEthData) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateFetchEthData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateFetchEthData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateFetchEthData proto.InternalMessageInfo

func (m *MsgUpdateFetchEthData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateFetchEthData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateFetchEthData) GetDataVal() string {
	if m != nil {
		return m.DataVal
	}
	return ""
}

type MsgUpdateFetchEthDataResponse struct {
}

func (m *MsgUpdateFetchEthDataResponse) Reset()         { *m = MsgUpdateFetchEthDataResponse{} }
func (m *MsgUpdateFetchEthDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateFetchEthDataResponse) ProtoMessage()    {}
func (*MsgUpdateFetchEthDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{3}
}
func (m *MsgUpdateFetchEthDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateFetchEthDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateFetchEthDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateFetchEthDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateFetchEthDataResponse.Merge(m, src)
}
func (m *MsgUpdateFetchEthDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateFetchEthDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateFetchEthDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateFetchEthDataResponse proto.InternalMessageInfo

type MsgDeleteFetchEthData struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteFetchEthData) Reset()         { *m = MsgDeleteFetchEthData{} }
func (m *MsgDeleteFetchEthData) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteFetchEthData) ProtoMessage()    {}
func (*MsgDeleteFetchEthData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{4}
}
func (m *MsgDeleteFetchEthData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteFetchEthData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteFetchEthData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteFetchEthData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteFetchEthData.Merge(m, src)
}
func (m *MsgDeleteFetchEthData) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteFetchEthData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteFetchEthData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteFetchEthData proto.InternalMessageInfo

func (m *MsgDeleteFetchEthData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteFetchEthData) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteFetchEthDataResponse struct {
}

func (m *MsgDeleteFetchEthDataResponse) Reset()         { *m = MsgDeleteFetchEthDataResponse{} }
func (m *MsgDeleteFetchEthDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteFetchEthDataResponse) ProtoMessage()    {}
func (*MsgDeleteFetchEthDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13fe6caccfe7d77, []int{5}
}
func (m *MsgDeleteFetchEthDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteFetchEthDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteFetchEthDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteFetchEthDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteFetchEthDataResponse.Merge(m, src)
}
func (m *MsgDeleteFetchEthDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteFetchEthDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteFetchEthDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteFetchEthDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateFetchEthData)(nil), "omni.omni.MsgCreateFetchEthData")
	proto.RegisterType((*MsgCreateFetchEthDataResponse)(nil), "omni.omni.MsgCreateFetchEthDataResponse")
	proto.RegisterType((*MsgUpdateFetchEthData)(nil), "omni.omni.MsgUpdateFetchEthData")
	proto.RegisterType((*MsgUpdateFetchEthDataResponse)(nil), "omni.omni.MsgUpdateFetchEthDataResponse")
	proto.RegisterType((*MsgDeleteFetchEthData)(nil), "omni.omni.MsgDeleteFetchEthData")
	proto.RegisterType((*MsgDeleteFetchEthDataResponse)(nil), "omni.omni.MsgDeleteFetchEthDataResponse")
}

func init() { proto.RegisterFile("omni/omni/tx.proto", fileDescriptor_f13fe6caccfe7d77) }

var fileDescriptor_f13fe6caccfe7d77 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcf, 0xcd, 0xcb,
	0xd4, 0x07, 0x13, 0x25, 0x15, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x9c, 0x20, 0xae, 0x1e,
	0x88, 0x90, 0x92, 0x43, 0x48, 0xa7, 0xa5, 0x96, 0x24, 0x67, 0xc4, 0xa7, 0x96, 0x64, 0xc4, 0xa7,
	0x24, 0x96, 0x24, 0x42, 0x94, 0x2a, 0x79, 0x73, 0x89, 0xfa, 0x16, 0xa7, 0x3b, 0x17, 0xa5, 0x26,
	0x96, 0xa4, 0xba, 0x81, 0x14, 0xb8, 0x96, 0x64, 0xb8, 0x24, 0x96, 0x24, 0x0a, 0x49, 0x70, 0xb1,
	0x27, 0x83, 0x44, 0xf3, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x90, 0x0c,
	0xc8, 0x80, 0xb0, 0xc4, 0x1c, 0x09, 0x26, 0x88, 0x0c, 0x94, 0xab, 0xa4, 0xcf, 0x25, 0x8b, 0xd5,
	0xb0, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xb0,
	0x79, 0x2c, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0xd1, 0x60, 0xdb, 0x43, 0x0b, 0x52, 0x88, 0xb7, 0x1d,
	0x62, 0x04, 0x13, 0xcc, 0x08, 0x64, 0xd7, 0x30, 0xa3, 0xba, 0x46, 0x1e, 0xec, 0x1a, 0x4c, 0xc3,
	0x61, 0xae, 0x51, 0x72, 0x04, 0xdb, 0xee, 0x92, 0x9a, 0x93, 0x4a, 0xae, 0xed, 0x50, 0x3b, 0x30,
	0x8d, 0x80, 0xd9, 0x61, 0xb4, 0x9a, 0x89, 0x8b, 0xd9, 0xb7, 0x38, 0x5d, 0x28, 0x81, 0x4b, 0x08,
	0x4b, 0x20, 0x2b, 0xe8, 0xc1, 0x63, 0x4a, 0x0f, 0x6b, 0xc8, 0x49, 0x69, 0x10, 0x52, 0x01, 0x0f,
	0xdb, 0x04, 0x2e, 0x21, 0x2c, 0x01, 0x89, 0x66, 0x03, 0xa6, 0x0a, 0x74, 0x1b, 0x70, 0x87, 0x17,
	0xc8, 0x06, 0x2c, 0x81, 0x85, 0x66, 0x03, 0xa6, 0x0a, 0x74, 0x1b, 0x70, 0x87, 0x96, 0x93, 0xf6,
	0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c,
	0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x09, 0xfa, 0x83, 0x92, 0x70, 0x05,
	0x34, 0xa1, 0x57, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x53, 0xb0, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xa5, 0x60, 0x99, 0x00, 0x02, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateFetchEthData(ctx context.Context, in *MsgCreateFetchEthData, opts ...grpc.CallOption) (*MsgCreateFetchEthDataResponse, error)
	UpdateFetchEthData(ctx context.Context, in *MsgUpdateFetchEthData, opts ...grpc.CallOption) (*MsgUpdateFetchEthDataResponse, error)
	DeleteFetchEthData(ctx context.Context, in *MsgDeleteFetchEthData, opts ...grpc.CallOption) (*MsgDeleteFetchEthDataResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateFetchEthData(ctx context.Context, in *MsgCreateFetchEthData, opts ...grpc.CallOption) (*MsgCreateFetchEthDataResponse, error) {
	out := new(MsgCreateFetchEthDataResponse)
	err := c.cc.Invoke(ctx, "/omni.omni.Msg/CreateFetchEthData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateFetchEthData(ctx context.Context, in *MsgUpdateFetchEthData, opts ...grpc.CallOption) (*MsgUpdateFetchEthDataResponse, error) {
	out := new(MsgUpdateFetchEthDataResponse)
	err := c.cc.Invoke(ctx, "/omni.omni.Msg/UpdateFetchEthData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteFetchEthData(ctx context.Context, in *MsgDeleteFetchEthData, opts ...grpc.CallOption) (*MsgDeleteFetchEthDataResponse, error) {
	out := new(MsgDeleteFetchEthDataResponse)
	err := c.cc.Invoke(ctx, "/omni.omni.Msg/DeleteFetchEthData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateFetchEthData(context.Context, *MsgCreateFetchEthData) (*MsgCreateFetchEthDataResponse, error)
	UpdateFetchEthData(context.Context, *MsgUpdateFetchEthData) (*MsgUpdateFetchEthDataResponse, error)
	DeleteFetchEthData(context.Context, *MsgDeleteFetchEthData) (*MsgDeleteFetchEthDataResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateFetchEthData(ctx context.Context, req *MsgCreateFetchEthData) (*MsgCreateFetchEthDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFetchEthData not implemented")
}
func (*UnimplementedMsgServer) UpdateFetchEthData(ctx context.Context, req *MsgUpdateFetchEthData) (*MsgUpdateFetchEthDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFetchEthData not implemented")
}
func (*UnimplementedMsgServer) DeleteFetchEthData(ctx context.Context, req *MsgDeleteFetchEthData) (*MsgDeleteFetchEthDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFetchEthData not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateFetchEthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateFetchEthData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateFetchEthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omni.omni.Msg/CreateFetchEthData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateFetchEthData(ctx, req.(*MsgCreateFetchEthData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateFetchEthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateFetchEthData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateFetchEthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omni.omni.Msg/UpdateFetchEthData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateFetchEthData(ctx, req.(*MsgUpdateFetchEthData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteFetchEthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteFetchEthData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteFetchEthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omni.omni.Msg/DeleteFetchEthData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteFetchEthData(ctx, req.(*MsgDeleteFetchEthData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "omni.omni.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFetchEthData",
			Handler:    _Msg_CreateFetchEthData_Handler,
		},
		{
			MethodName: "UpdateFetchEthData",
			Handler:    _Msg_UpdateFetchEthData_Handler,
		},
		{
			MethodName: "DeleteFetchEthData",
			Handler:    _Msg_DeleteFetchEthData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "omni/omni/tx.proto",
}

func (m *MsgCreateFetchEthData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFetchEthData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFetchEthData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataVal) > 0 {
		i -= len(m.DataVal)
		copy(dAtA[i:], m.DataVal)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataVal)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateFetchEthDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateFetchEthDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateFetchEthDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateFetchEthData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateFetchEthData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateFetchEthData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DataVal) > 0 {
		i -= len(m.DataVal)
		copy(dAtA[i:], m.DataVal)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DataVal)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateFetchEthDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateFetchEthDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateFetchEthDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteFetchEthData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteFetchEthData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteFetchEthData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteFetchEthDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteFetchEthDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteFetchEthDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateFetchEthData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DataVal)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateFetchEthDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateFetchEthData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.DataVal)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateFetchEthDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteFetchEthData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteFetchEthDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateFetchEthData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFetchEthData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFetchEthData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateFetchEthDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateFetchEthDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateFetchEthDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateFetchEthData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateFetchEthData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateFetchEthData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataVal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataVal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateFetchEthDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateFetchEthDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateFetchEthDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteFetchEthData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteFetchEthData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteFetchEthData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteFetchEthDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteFetchEthDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteFetchEthDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
